/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef idl_CONSTANTS_H
#define idl_CONSTANTS_H

#include "idl_types.h"



class idlConstants {
 public:
  idlConstants();

};

extern const idlConstants g_idl_constants;



#endif
