/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef text_CONSTANTS_H
#define text_CONSTANTS_H

#include "text_types.h"



class textConstants {
 public:
  textConstants();

};

extern const textConstants g_text_constants;



#endif
